name: CI/CD for Flask App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Debug secrets
        run: |
          echo "USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "PASSWORD LENGTH=${{ secrets.DOCKER_PASSWORD != '' && secrets.DOCKER_PASSWORD != null && secrets.DOCKER_PASSWORD | size || 'EMPTY' }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8s:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8s:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
